### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by gabe56f** [rakion99/Axon#10]
Crashes ROBLOX...

**Comment by Shadow997** [comment]
It's easy to fix. When you type the script, do:
spawn (function()
Your script
end)

**Comment by Jack412** [comment]
what do i need to include?

**Comment by DEGUYWITHPANTSU** [comment]
when inject it crashes

**Comment by Jack412** [comment]
where the fuck do i copy and paste the stuff?

**Comment by CryptonicMods** [comment]
idk how to even work the thing

**Comment by rakion99** [comment]
Learn C++, Learn Reverse Engineering, Learn How to use ida disassembler, Learn Lua after that you will know
