### ISSUE TITLE
How To find the Addresses

### ISSUE THREAD

**Issue by 32two64** [rakion99/Axon#15]
I found some addresses, but there are some I cant find. Can you help us out. NOT ASKING TO RELEASE UPDATED SOURCE, BUT JUST HOW TO UPDATE IT OURSELVS

**Comment by rakion99** [comment]
Learn Reverse Engineering, Learn How to use ida disassembler, use lua 5.1.4 source as reference(like this http://stevedonovan.github.io/lua-5.1.4/) then you will know
