### ISSUE TITLE
if roblox updates is axon then patched?

### ISSUE THREAD

**Issue by VenomousNoodle** [rakion99/Axon#16]
if roblox updates is axon then patched?

**Comment by gabe56f** [comment]
yes

**Comment by VenomousNoodle** [comment]
when is it updated?

**Comment by rakion99** [comment]
"unpatch" 🤦‍♂️ all are wrong how you will unpatch something that isnt broken? all should know what patched and outdated mean different things, just find new address and that shit to update it simple or pay someone to do it 4 u

**Comment by LocalCommunist** [comment]
delete the source, you don´t even know how to update it lmao

**Comment by VenomousNoodle** [comment]
no but i have the adreses!

**Comment by rakion99** [comment]
updated since all are New Users :U
