### ISSUE TITLE
[REQ] Please give me dll

### ISSUE THREAD

**Issue by ErenYeagerZ** [rakion99/Axon#18]
can build dll for me i can't build dll it error

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

**Comment by rakion99** [comment]
Soon also i will add a simple ui too

**Comment by VenomousNoodle** [comment]
it doesnt matter you cant use it its broken :(

**Comment by CryptonicMods** [comment]
You need to unpatch it yourself.

**Comment by rakion99** [comment]
both are wrong,

**Comment by Doller3795** [comment]
Update your visual studio and find for that sdk or something that works for axon
