### ISSUE TITLE
Please give me right addresses

### ISSUE THREAD

**Issue by JostynCrafter** [rakion99/Axon#22]
please can I get the correct addresses for this update would be very helpful or can you explain how I get them on my own?

**Comment by rakion99** [comment]
Learn Reverse Engineering, Learn How to use ida disassembler, use lua 5.1.4 source as reference(like this http://stevedonovan.github.io/lua-5.1.4/) then you will know
or you can buy them from my selly link https://selly.gg/p/d188a7b3 for $5 for undefined time cheap and safe
