### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by cameron6542** [rakion99/Axon#28]
So i have downloaded this and when opening the Axon dll's sln i receive at least 1000 thousand errors which means i can't build the sln to a dll which means i can't self update addresses. Is there any fix for this? It has been annoying me all day and i can't find anything anywhere except other people that have the same problem with no solution @rakion99 [Error List](https://imgur.com/a/0HWqJkC)

**Comment by rakion99** [comment]
ya the fix is really simple but since you don't know how to code you didn't figured it out so delete the source and **learn c++**
