### ISSUE TITLE
No Axon.dll

### ISSUE THREAD

**Issue by DopTop** [rakion99/Axon#30]
When I Build the exe it doesnt make axon.dll. How do i get this axon.dll

**Comment by rakion99** [comment]
looooooool read what you said 🤣 😂 
![image](https://user-images.githubusercontent.com/1360084/43288534-c3e303c4-90ed-11e8-8cdb-8c0631451dfe.png)

ok out of the memes, learn c++, lua c api and reverse engineering(DLL) and c#(UI)
