### ISSUE TITLE
Injection Failed! Maybe you are missing something or took more time to check if was ready or other stuff. HELP!!!

### ISSUE THREAD

**Issue by OofExpoitz** [rakion99/Axon#36]
Yes, im trying to make a roblox unrestricted lua executor, when this happend:
![thishappened](https://user-images.githubusercontent.com/42442503/44212889-2e2df280-a132-11e8-9685-3faea6b84954.PNG)
I set the lua pipe exactly the same... i did not edit any of the source code! Please help someone!

**Comment by OofExpoitz** [comment]
How do I learn it? LOL, I already know 3 programming languages. Man, This is going to be hard. BTW is Reverse Engineering programming?

**Comment by OofExpoitz** [comment]
Oh and where does rakion99 say this? Also did you make your own unrestricted lua executor?

**Comment by rakion99** [comment]
in every invalid issue like yours....
so Learn c++ and reverse engineering and this will be easy asf
