### ISSUE TITLE
How would I find r_luaL_ref?

### ISSUE THREAD

**Issue by SuperSkidder911** [rakion99/Axon#39]
I found all other addresses except for this one, I'm stuck on it. If someone could lead me in the right direction a bit I'd be happy. Thanks

**Comment by Doller3795** [comment]
IDA String "WeakThreadRef::addRef() %p for node %p"
Pseudocode 2 lines up at else

v4[3] = sub_XXXXXX(v4[2], -10000);
^ This might be changed but will be similar, XXXXXX is the address

**Comment by rakion99** [comment]
use lua source annotated......
