### ISSUE TITLE
Rel Source Code Updates?

### ISSUE THREAD

**Issue by 32two64** [rakion99/Axon#6]
Maybe Release The Newer Updated Source Codes, So its easier for us to understand. If Not, Can you make a tutorial on how to update the source?

**Comment by LocalCommunist** [comment]
how about you unpatch it yourself he aint gonna do that for yo ass "update the newer updated code" lol just update the addresses noob

**Comment by DEGUYWITHPANTSU** [comment]
idk where to paste the addresses to?

**Comment by rakion99** [comment]
lol 🤦‍♂️ or payme and ill update it 4 u 😉
